return {
  ["fireflash"] = {
    usedefaultexplosions = false,
	spikes = {
		air                = false,
		class              = [[CExploSpikeProjectile]],
		count              = 1,
		ground             = true,
		water              = false,
		properties = {
			alwaysVisible      = false,
			length 				= 30,
			width					= 20,
			alpha					= 1,
			alphaDecay 			= 0.2,
			lengthGrowth			= 2.8,
			dir 				= [[r3 -1.5,r3 -1.5, r3-1.5]],
			color 				= [[1, 0, 0]],
			pos					= [[0, 0,0]],
		},
	},
  },
  ["sickfires"] = {
    fire = {
      class              = [[CExpGenSpawner]],
      count              = 10,
      nounit             = 1,
      ground             = true,
      water              = true,
	  air                = true,
      properties = {
        delay              = [[d0.1y1 i1x1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:fire]],
        pos                = [[0, 0, 0]],
        damage             = [[d1]],
      },
    },
  },
  ["fire"] = {
    usedefaultexplosions = false,
    expand = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = false,
        heat               = [[d1 30]],
        heatfalloff        = [[10]],
        maxheat            = [[d2]],
        pos                = [[r10 -5,r10 -5,r10 -5]],
        size               = [[15]],
        sizegrowth         = [[0.2]],
        speed              = [[0, 0.2, 0]],
      },
    },
    contract = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = false,
        heat               = [[d1 30]],
        heatfalloff        = [[10]],
        maxheat            = [[d3]],
        pos                = [[r10 -5,r10 -5,r10 -5]],
        size               = [[15]],
        sizegrowth         = [[-0.5]],
        speed              = [[0, 0.1, 0]],
      },
    },
	flame = {
		air                = false,
		class              = [[CExploSpikeProjectile]],
		count              = 1,
		ground             = true,
		water              = false,
		properties = {
			alwaysVisible      = false,
			length 				= 5,
			width				= 10,
			alpha				= 1,
			alphaDecay 			= [[d0.1p-1.05]],
			lengthGrowth		= [[d0.01]],
			dir 				= [[0,2.5 i0.8, 0]],
			color 				= [[1, 0, 0]],
			pos					= [[0, 0, 0]],
		},
	},
	core = {
		air                = false,
		class              = [[CExploSpikeProjectile]],
		count              = 1,
		ground             = true,
		water              = false,
		properties = {
			alwaysVisible      = false,
			length 				= 5,
			width				= 10,
			alpha				= 1,
			alphaDecay 			= [[d0.1p-1.1]],
			lengthGrowth		= [[d0.005]],
			dir 				= [[0,2.5 i0.8, 0]],
			color 				= [[1, 0.15, 0]],
			pos					= [[0, 0, 0]],
		},
	},
  },

}

