return {
  ["ufoblast"] = {
	spikes = {
		air                = true,
		class              = [[CExploSpikeProjectile]],
		count              = 5,
		ground             = true,
		water              = true,
		properties = {
			alwaysVisible      = false,
			length 				= 50,
			width				= 50,
			alpha				= 1,
			alphaDecay 			= 0.2,
			lengthGrowth		= 5.6,
			dir 				= [[r30 -15,r30 -15, r30 -15]],
			color 				= [[0, 1, 1]],
			pos					= [[0, 0,0]],
		},
	},
	spikes = {
		air                = true,
		class              = [[CExploSpikeProjectile]],
		count              = 5,
		ground             = true,
		water              = true,
		properties = {
			alwaysVisible      = false,
			length 				= 50,
			width				= 50,
			alpha				= 1,
			alphaDecay 			= 0.2,
			lengthGrowth		= 5.6,
			dir 				= [[r30 -15,r30 -15, r30 -15]],
			color 				= [[0, 1, 1]],
			pos					= [[0, 0,0]],
		},
	},
    pop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 0.4,
        maxheat            = 15,
        pos                = [[-20 r40, -20 r40, -20 r40]],
        size               = 50,
        sizegrowth         = 10,
        sizegrowthmod      = 1.1,
        speed              = [[0, 1 0, 0]],
        texture            = [[flare]],
      },
    },
    pop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 5,
      ground             = true,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.30000001192093,
        [3]  = 0,
      },
      properties = {
        heat               = 10,
        heatfalloff        = 0.5,
        maxheat            = 15,
        pos                = [[-25 r50, 5, -25 r50]],
        size               = [[20 r-10]],
        sizegrowth         = 2,
        sizegrowthmod      = -0.1,
        speed              = [[-1 r2, 1 0, -1 r2]],
        texture            = [[smoke_orange]],
      },
    },
    pop3 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 5,
      ground             = true,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.30000001192093,
        [3]  = 0,
      },
      properties = {
        heat               = 15,
        heatfalloff        = 0.5,
        maxheat            = 15,
        pos                = [[0 0 0]],
        size               = [[50]],
        sizegrowth         = 10,
        sizegrowthmod      = 1.2,
        speed              = [[-1 r2, 1 0, -1 r2]],
        texture            = [[explosionwave]],
      },
    },
    smoke = {
      air                = true,
      count              = 30,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.04,
        color              = 0.1,
        pos                = [[-80 r40, -80 r40, -80 r40]],
        size               = 16,
        sizeexpansion      = 1.6,
        speed              = [[1 r-2, -1 r2.3, 1r-2]],
        startsize          = 2,
      },
    },
  },
}
